#!/usr/bin/env node
/**
 * Turn the reviewable prompt markdown into a TypeScript module.
 *
 * The prompt lives in `.md` so it can be read and reviewed as prose rather than
 * as a string literal (docs/06). It cannot be imported directly: Node has no
 * loader for markdown, and core has to run in both hosts unmodified.
 *
 * So it is generated, and the generated file is committed. A test re-runs this
 * and fails if the result differs, which is what stops the two drifting.
 *
 *   node scripts/build-prompts.mjs [--check]
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const promptDir = join(root, "packages/core/src/agent/prompts");
const outFile = join(promptDir, "index.ts");

const { values } = parseArgs({
  options: { check: { type: "boolean", default: false } },
});

const names = (await readdir(promptDir)).filter((n) => n.endsWith(".md")).sort();

const parts = [
  "// GENERATED by scripts/build-prompts.mjs — do not edit.",
  "//",
  "// The source of truth is the .md file beside this one, which exists so the",
  "// prompt can be reviewed as prose. Run `pnpm build-prompts` after editing it.",
  "",
];

for (const name of names) {
  const text = await readFile(join(promptDir, name), "utf8");
  const constant = name
    .replace(/\.md$/, "")
    .replace(/[^a-z0-9]+/gi, "_")
    .toUpperCase();
  parts.push(`export const ${constant}_PROMPT = ${JSON.stringify(text)};`, "");
}

const generated = parts.join("\n");

if (values.check) {
  const existing = await readFile(outFile, "utf8").catch(() => "");
  if (existing !== generated) {
    process.stderr.write(
      "prompts are out of date: run `pnpm build-prompts` after editing the .md\n",
    );
    process.exit(1);
  }
  process.stderr.write("prompts are up to date\n");
} else {
  await writeFile(outFile, generated, "utf8");
  process.stderr.write(`wrote ${String(names.length)} prompts to ${outFile}\n`);
}
